apiVersion: v1
kind: Service
metadata:
  name: go-loadbalancer
  namespace: go-namespace
spec:
  selector:
    app: goweb
  type: LoadBalancer
  # loadBalancerIP: 10.10.130.145
  ports:
  - port: 80
    targetPort: 8080