apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: go-namespace
  labels:
    app: go-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: aleynikov1988/go_app:v0.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          mountPath: "/usr/secrets/"
          readOnly: true
        - name: pvc-volume
          mountPath: "/data"
        env:
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: color
      volumes:
      - name: secret-volume
        secret:
          secretName: go-secret
      - name: pvc-volume
        persistentVolumeClaim:
          claimName: go-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  type: NodePort
  selector:
    app: goapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30007
