apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-pvc
  namespace: go-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "default"
  resources:
    requests:
      storage: 10Gi