apiVersion: v1
kind: Pod
metadata:
  name: go-pod
  namespace: go-namespace
  labels:
    app: goweb
spec:
  containers:
  - name: go-app
    image: aleynikov1988/go_app:v0.2
    ports:
    - protocol: TCP
      containerPort: 8080