apiVersion: batch/v1
kind: Job
metadata:
  name: py-job
  namespace: py-namespace
spec:
  template:
    spec:
      containers:
      - name: py-hello
        image: aleynikov1988/py_app:v0.2
        env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: py-secret
              key: name
      restartPolicy: Never